package one;

public class ArithmeticException {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
/**
		try
		{
		int i=20;
		
		System.out.println("The result is:"+(i/0));
		}
		
		catch(ArithmeticException  e)
		{
			System.out.println("The exception is:"+e);
		}
	}
**/
      
		
		
}
}